# Generated by Django 3.2.9 on 2021-11-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livestream',
        ),
    ]
