# Generated by Django 3.2.9 on 2021-11-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='store',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='store',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='store',
            name='photo_6',
        ),
        migrations.AddField(
            model_name='store',
            name='book_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
