# Generated by Django 3.2.9 on 2021-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Livestream_Title', models.CharField(max_length=45, verbose_name='Livestream Title')),
                ('Livestream_URL', models.CharField(max_length=45, verbose_name='Livestream URL')),
                ('Livestream_Image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Livestream',
                'verbose_name_plural': 'Livestreams',
            },
        ),
    ]
